name: agsapp
description: AGS Sınav Hazırlık - Tarih, Coğrafya, Eğitim ve Mevzuat konularında kapsamlı soru bankası
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  get_it: ^7.6.4
  dartz: ^0.10.1
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  google_fonts: ^6.1.0
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/questions/tarih/
    - assets/questions/tarih/islamiyet_oncesi_turk_tarihi/
    - assets/questions/tarih/ilk_turk_islam_devletleri/
    - assets/questions/tarih/anadolu_selcuklu/
    - assets/questions/tarih/kurulus_donemi/
    - assets/questions/tarih/osmanli_yukselme_donemi/
    - assets/questions/tarih/osmanli_kulturu/
    - assets/questions/tarih/duraklama_donemi/
    - assets/questions/tarih/dagilma_1_dunya_savasi/
    - assets/questions/tarih/dagilma_donemi/
    - assets/questions/tarih/cagdas_turk_ve_dunya_tarihi/
    - assets/questions/tarih/milli_mucadele_hazirlik/
    - assets/questions/tarih/milli_mucadele/
    - assets/questions/tarih/ataturk_donemi/
    - assets/questions/cografya/
    - assets/questions/cografya/sanayi/
    - assets/questions/cografya/nufus/
    - assets/questions/cografya/yer_sekilleri/
    - assets/questions/cografya/cografi_konum/
    - assets/questions/cografya/iklim/
    - assets/questions/cografya/daglar/
    - assets/questions/cografya/tarim/
    - assets/questions/cografya/projeler/
    - assets/questions/cografya/turizm_ticaret_ulasim/
    - assets/questions/cografya/madencilik/ 
    - assets/questions/egitim/
    - assets/questions/egitim/egitim_ve_ogretim_teknolojileri/
    - assets/questions/egitim/egitimin_temel_kavramlari/
    - assets/questions/egitim/egitimin_temelleri_ve_kuramlar/
    - assets/questions/egitim/maarif_modeli/
    - assets/questions/egitim/turk_milli_egitim_sistemi/
    - assets/questions/mevzuat/
    - assets/questions/mevzuat/1739_sayili_milli_egitim_temel_kanunu/
    - assets/questions/mevzuat/1982_anayasasi_genel_esaslar_ve_devletin_nitelikleri/
    - assets/questions/mevzuat/222_sayili_ilkogretim_ve_egitim_kanunu/
    - assets/questions/mevzuat/7528_sayili_ogretmenlik_meslek_kanunu_ozellikleri/
    - assets/questions/mevzuat/idare/
    - assets/questions/mevzuat/temel_hak_ve_hurriyetler/
    - assets/questions/mevzuat/yargi/
    - assets/questions/mevzuat/yasama/
    - assets/questions/mevzuat/yurutme/